name: Prebuild
on:
  workflow_dispatch:
jobs:
  prebuild:
    strategy:
      matrix:
        node: [20]
        os: [ubuntu-22.04, macos-12, macos-14, windows-2022]
        include:
        - os: ubuntu-22.04
          platform: linux
          arch: x64
        - os: macos-12
          platform: darwin
          arch: x64
        - os: macos-14
          platform: darwin
          arch: arm64
        - os: windows-2022
          platform: win32
          arch: x64
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.platform }}-${{ matrix.arch }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
    - run: npm install -g bare-dev
    - run: bare-dev configure --platform ${{ matrix.platform }} --arch ${{ matrix.arch }}
    - run: bare-dev build
    - uses: actions/upload-artifact@v4
      if: ${{ matrix.platform == 'linux' || matrix.platform == 'darwin' }}
      with:
        name: ${{ matrix.platform }}-${{ matrix.arch }}
        path: build/bin/bare
    - uses: actions/upload-artifact@v4
      if: ${{ matrix.platform == 'win32' }}
      with:
        name: ${{ matrix.platform }}-${{ matrix.arch }}
        path: |
          build/bin/Release/bare.exe
          build/bin/Release/bare.lib
