name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        node: [lts/*]
        os: [ubuntu-latest, macos-latest, windows-latest]
        android-ndk: [26.1.10909125]
        android-api: [34]
        include:
        - os: ubuntu-latest
          platform: linux
          arch: x64
        - os: ubuntu-22.04
          platform: android
          arch: x64
        - os: ubuntu-22.04
          platform: android
          arch: ia32
        - os: ubuntu-22.04
          platform: android
          arch: arm64
        - os: ubuntu-22.04
          platform: android
          arch: arm
        - os: macos-latest
          platform: darwin
          arch: x64
        - os: macos-latest
          platform: ios
          arch: x64
        - os: windows-latest
          platform: win32
          arch: x64
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.platform }}-${{ matrix.arch }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/cache@v4
      with:
        path: corestore
        key: corestore-${{ matrix.platform }}-${{ matrix.arch }}
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}

    - run: npm install -g bare-dev

    - run: bare-dev configure --debug --platform ${{ matrix.platform }} --arch ${{ matrix.arch }}
      if: ${{ matrix.platform == 'linux' || matrix.platform == 'darwin' || matrix.platform == 'win32' }}

    - run: bare-dev configure --debug --platform ${{ matrix.platform }} --arch ${{ matrix.arch }} --simulator
      if: ${{ matrix.platform == 'ios' }}

    - run: bare-dev configure --debug --platform ${{ matrix.platform }} --arch ${{ matrix.arch }} --android-ndk ${{ matrix.android-ndk }} --android-api ${{ matrix.android-api }}
      if: ${{ matrix.platform == 'android' }}

    - run: bare-dev build --debug

    - run: bare-dev test --debug
      if: ${{ matrix.platform == 'linux' || matrix.platform == 'darwin' || matrix.platform == 'win32' }}
